name: dotnet-build
on: 
  push: 
    branches: [ "main" ]
  schedule::
    - cron: `30 6 * * 5`

jobs:
  build:
    name: Github4Woman
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout no meu código usando uses
      uses: actions/checkout@v4

    - name: Comando usando run
      run: echo "Desafio "